chore(deps): upgrade dfx to 0.25.1 and fix quill upgrade (#474)
# Motivation

We want to keep our `dfx` dependency up to date. When we tried to
upgrade `dfx`, `snsdemo` failed due to incompatibilities with the
existing version of `quill`, making an upgrade necessary. This upgrade
resulted in a different response when creating a neuron for proposals
and voting, so we needed to update our process for handling the results
from `quill`.

New response :

```
ERROR: Could not find neuron in response:
Sending message with

  Call type:   update
  Sender:      qwxyj-oky6g-4tume-5535q-iay2u-ucexk-btigu-6xcmz-pehp5-5duog-kae
  Canister id: ryjl3-tyaaa-aaaaa-aaaba-cai
  Method name: transfer
  Arguments:   (
  record {
    to = blob "\ba\c4\cf\76\4a\74\51\f4\85\2d\5c\57\16\54\2f\e1\d2\7a\1a\bb\39\ad\98\39\5b\f7\81\3a\5e\cb\85\2b";
    fee = record { e8s = 10_000 : nat64 };
    memo = 49 : nat64;
    from_subaccount = null;
    created_at_time = opt record {
      timestamp_nanos = 1_744_038_244_913_902_969 : nat64;
    };
    amount = record { e8s = 50_000_000_000_000_000 : nat64 };
  },
)
Request ID: 0xe9aa464715a2015d76863959e9dfc77c8b3edad6213fc8b93a1f9ded5e070141
The request is being processed...
The request is being processed...
Transfer sent at block index 6
Sending message with

  Call type:   update
  Sender:      2vxsx-fae
  Canister id: rrkah-fqaaa-aaaaa-aaaaq-cai
  Method name: manage_neuron
  Arguments:   (
  record {
    id = null;
    command = opt variant {
      ClaimOrRefresh = record {
        by = opt variant {
          MemoAndController = record {
            controller = opt principal "qwxyj-oky6g-4tume-5535q-iay2u-ucexk-btigu-6xcmz-pehp5-5duog-kae";
            memo = 49 : nat64;
          }
        };
      }
    };
    neuron_id_or_subaccount = null;
  },
)
Request ID: 0xe5b9927e3e8ed64f25d198a2f187b4e5e3a7d154e6c7bcc864b45b94c6179d44
The request is being processed...
The request is being processed...
Successfully staked ICP in neuron 7962789023331170626
```

## Changes

- Bump `dfx` to 0.25.1  
- Bump `quill` to 0.5.3  
- Update `dfx-neuron-create` logic to extract neuronId from the quill
response .