fix(deploy): fix by correcting ckbtc_kyt canister init argument type and bumping versions (#491)
# Motivation

[Updating the IC commit](https://github.com/dfinity/snsdemo/pull/490)
[failed](https://github.com/dfinity/snsdemo/actions/runs/14963341344/job/42028924218?pr=490)
with
```
Error: Failed while trying to deploy canisters.
Caused by: Failed while trying to install all canisters.
Caused by: Failed to install wasm module to canister 'ckbtc_kyt'.
Caused by: Failed to create argument blob.
Caused by: Invalid data: Unable to serialize Candid values: Invalid data: Unable to serialize Candid values: type mismatch: variant {
  InitArg = record {
    num_subnet_nodes = 1;
    check_mode = variant { AcceptAll };
    btc_network = variant { mainnet };
  }
} cannot be of type opt variant { UpgradeArg : opt UpgradeArg; InitArg : InitArg }
```
due a change in IC that made `InitArgs`
[optional](https://github.com/dfinity/ic/commit/a121d18e91cb7f31d401bd59e1592cb28861f318).

# Changes

1. Mark the payload as `opt`.  
2. Update the IC version to #493, as #496 fails on macOS. 👇  
3. Skip tests against the latest version for now, as they are failing
for
[macOS](https://github.com/dfinity/snsdemo/pull/491/checks?sha=c1564d16c9d940ea71dd00871c30c9f52b145c38).
4. Update nns-extensions and sns-extensions to the latest version, as
they no longer support protobuf in favor of candid.

# Tested

- Created a snapshot locally and successfully ran nns-dapp against it.
- Created a snapshot in the CI.