Set canister IDs for nns-dapp and internet_identity (#139)
# Motivation

These lines were removed in
https://github.com/dfinity/snsdemo/commit/2f88565f97c50dbe1a42452bec0d76d29085ec71
After this, created snapshots could no longer be used in nns-dapp CI
because it didn't know how to install nns-dapp:

https://github.com/dfinity/nns-dapp/actions/runs/4798582311/jobs/8537065686?pr=2361
```
Error: Failed to determine id for canister 'nns-dapp'.
Caused by: Failed to determine id for canister 'nns-dapp'.
  Cannot find canister id. Please issue 'dfx canister create nns-dapp'.
Error: Process completed with exit code 255.
```

With these lines restored, nns-dapp CI can once again install these
canisters:

https://github.com/dfinity/nns-dapp/actions/runs/4810990614/jobs/8565031409
(Sadly the Firefox tests are quite flaky.)

# Change

Restore the removed lines that set the canister IDs.

# Tested

Created a snapshot on this branch and ran nns-dapp CI with it.