Retry snapshot health check if it doesn't pass immediately (#356)
# Motivation

When [updating](https://github.com/dfinity/snsdemo/pull/353) to the
latest IC commit, CI started
[failing](https://github.com/dfinity/snsdemo/actions/runs/9178449234/job/25261424970)
with
```
Certificate is stale (over 240s). Is the computer's clock synchronized?
```
right after starting the snapshot.
If we wait for some time, the issue goes away, presumably because the
replica creates a new certificate.

I tried bisecting to find out what caused it but it's extremely slow and
not 100% consistent, which makes it hard to find.
I also asked on Slack
([here](https://dfinity.slack.com/archives/CH4CADCJX/p1716298787451049))
but couldn't reach a definitive conclusion.

# Changes

Retry the health check for up to 5 minutes if it doesn't pass
immediately.

# Tested

1. Ran `dfx start --clean` and started the health check, seeing it fail.
2. Ran `dfx-nns-install`, `dfx-nns-import` and
`dfx-software-sns-aggregator-install`.
3. Eventually the health check passed.

```
Error: Cannot find canister id. Please issue 'dfx canister create nns-governance'.
Not healthy yet. Time remaining:      600 seconds
Error: Cannot find canister id. Please issue 'dfx canister create nns-governance'.
Not healthy yet. Time remaining:      595 seconds
...
Not healthy yet. Time remaining:      500 seconds
Controllers: r7inp-6aaaa-aaaaa-aaabq-cai
Module hash: 0x54d1ff121346878bc6c7f100b08314f62645962bf97df4c7e27d5c06a9467945
Controllers: r7inp-6aaaa-aaaaa-aaabq-cai
Module hash: 0x5646a738fdeebcc23dfb499eba84fac074f2ed34bd1c7e81088867a264c48bfe
Error: Cannot find canister id. Please issue 'dfx canister create sns_aggregator'.
Not healthy yet. Time remaining:      495 seconds
...
Not healthy yet. Time remaining:      470 seconds
Controllers: r7inp-6aaaa-aaaaa-aaabq-cai
Module hash: 0x54d1ff121346878bc6c7f100b08314f62645962bf97df4c7e27d5c06a9467945
Controllers: r7inp-6aaaa-aaaaa-aaabq-cai
Module hash: 0x5646a738fdeebcc23dfb499eba84fac074f2ed34bd1c7e81088867a264c48bfe
Error: Cannot find canister id. Please issue 'dfx canister create sns_aggregator'.
Not healthy yet. Time remaining:      465 seconds
Controllers: r7inp-6aaaa-aaaaa-aaabq-cai
Module hash: 0x54d1ff121346878bc6c7f100b08314f62645962bf97df4c7e27d5c06a9467945
Controllers: r7inp-6aaaa-aaaaa-aaabq-cai
Module hash: 0x5646a738fdeebcc23dfb499eba84fac074f2ed34bd1c7e81088867a264c48bfe
Controllers: bnz7o-iuaaa-aaaaa-qaaaa-cai vja4n-apfdk-zojbf-rib7x-tnjsq-m5wti-tqnxm-ydwq6-dxy46-yotiw-iqe
Module hash: None
Controllers: 2vxsx-fae vja4n-apfdk-zojbf-rib7x-tnjsq-m5wti-tqnxm-ydwq6-dxy46-yotiw-iqe
Module hash: 0x6876b5878ef1c4737326aa074e5ebb773f4b126c5df17e167096af2df872f378
Controllers: 2vxsx-fae vja4n-apfdk-zojbf-rib7x-tnjsq-m5wti-tqnxm-ydwq6-dxy46-yotiw-iqe
Module hash: 0xcf5c88aa54d8ac43aa361f01231d5adb2dbcbf7dcd6b75c364e59ad84dc414c3
Basic health check passes
```